# Taps
tap 'homebrew/cask'
tap 'homebrew/bundle'

# Install GNU core utilities (those that come with macOS are outdated)
brew 'coreutils'

# Install Tools
brew 'grep'
brew 'awscli'
brew 'diff-so-fancy'
brew 'fzf'
brew 'findutils'
brew 'git'
brew 'gh'
brew 'gnu-sed'
brew 'htop'
brew 'kubernetes-cli'
brew 'k9s'
brew 'helm'
brew 'nmap'
brew 'neovim'
brew 'zellij'
brew 'wget'

# Development
brew 'mysql'
brew 'openssl'
brew 'postgresql@15'
brew 'tflint'
brew 'hadolint'
brew 'shellcheck'
brew 'yarn'
brew 'colima'
brew 'docker'
brew 'docker-buildx'
brew 'docker-compose'

# Font
cask 'font-jetbrains-mono-nerd-font'
cask 'alacritty'
cask 'beekeeper-studio'
cask 'chromedriver'
cask 'maccy'
