# Taps
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'

# Install ZSH
brew 'zsh'

# Install GNU core utilities (those that come with macOS are outdated)
brew 'coreutils'

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew 'findutils'

# Install Bash 4
brew 'bash'

# Install more recent versions of some macOS tools
brew 'grep'

# Install Binaries
# brew 'awscli'
brew 'git'
brew 'node'
brew 'wget'
brew 'parallel'
brew 'fzf'

# Development
brew 'php72'
brew 'php72-xdebug'
brew 'mysql'
brew 'go'
brew 'openssl'
brew 'node'
brew 'nvm'
brew 'rbenv'
brew 'python'
brew 'python3'
brew 'terraform'
brew 'packer'
brew 'erlang'
brew 'elixir'
brew 'yarn'
brew 'swiftlint'

# Tools
brew 'htop'
brew 'gnu-sed'
brew 'diff-so-fancy'
brew 'httping'
brew 'kops'
brew 'kubernetes-cli'
brew 'nmap'
brew 'vim'
brew 'zplug'

# Apps
# cask 'docker'
# cask 'firefox'
# cask 'google-chrome'
# cask 'google-chrome-canary'
# cask 'visual-studio-code'
# cask 'java'
# cask 'iterm2'
# cask 'sequel-pro'
# cask 'spotify'
# cask 'slack'
# cask 'tunnelbear'
# cask 'postman'
# cask 'insomnia'
# cask 'vlc'
# cask 'spectacle'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vagrant'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlstephen'

