k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  ui:
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    noIcons: false
    skin: gruvbox-dark
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.36.1
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
