set -g mouse on

bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

setw -g xterm-keys on

# Scroll History
set -g history-limit 10000

# Set ability to capture on start and restore on exit window data when running an application
setw -g alternate-screen on

# Lower escape timing from 500ms to 50ms for quicker response to scroll-buffer access.
set -s escape-time 10

# 256 colors
set -g default-terminal "screen-256color"

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n C-M-Left select-pane -L
bind -n C-M-Down select-pane -D
bind -n C-M-Up select-pane -U
bind -n C-M-Right select-pane -R

# switch windows using Shift-arrow without prefix
bind-key -n S-Up set-option -g status
bind-key -n S-Down set-option -g status
bind -n S-Left  previous-window
bind -n S-Right next-window

######################
### DESIGN CHANGES ###
######################
set-option -g status-position bottom
set-option -g status-fg white
set-option -g status-bg default
set-option -g status-attr default
set-window-option -g window-status-fg "#666666"
set-window-option -g window-status-bg default
set-window-option -g window-status-attr default
set-window-option -g window-status-current-fg "#40b2e0"
set-window-option -g window-status-current-bg "#101010"
set-window-option -g window-status-current-attr default
set-option -g message-fg white
set-option -g message-bg black
set-option -g message-attr bright
setw -g window-status-current-format '#W'
setw -g window-status-format '#W'
set -g status-left ""
set -g status-justify left
set -g status-right-length 200
set -g status-right ""
